# file is synced from cove-workflow

##################################################################
# HOW TO CUSTOMIZE A dependabot.yml IN A REPO
#
# 1. remove the repository from the sync list here:
#       https://github.com/livelyhood/cove-workflows/blob/main/.github/sync.yml
# 2. change dependabot.yml in your repo
#
# dependabot configuration options:
#    https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
#
###################################################################

version: 2
registries:
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{ secrets.NPM_TOKEN_READ_ONLY }}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "15:00" # UTC
    commit-message:
      prefix: chore
      prefix-development: chore
    groups:
      all:
        update-types:
          - "major"
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-npmjs
    schedule:
      interval: "weekly"
      day: "friday"
      time: "15:00" # UTC
    commit-message:
      prefix: chore
      prefix-development: chore
    groups:
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
